name: okra
description: An app for text readability and comprehension experiments.

publish_to: 'none'

version: 0.2.4-alpha

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^2.1.0
  barcode_scan: ^3.0.0
  flutter_markdown: ^0.4.3
  http: ^0.12.2
  intl: ^0.17.0
  just_audio: ^0.5.6
  localstorage: ^3.0.0
  package_info_plus: ^0.6.4
  provider: ^4.3.2
  tekartik_qrscan_flutter_web:
    git:
      url: git://github.com/tekartik/app_camera.dart
      path: qrscan_flutter_web
      ref: dart2
    version: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.9.2
  test: ^1.15.7
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - packages/tekartik_js_qr/js_qr.js
    - assets/images/balloon.png
    - assets/images/balloon_popped.png

flutter_intl:
  enabled: true

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/icon.png
