name: Test

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.13.0'
      - run: dart format -o none --set-exit-if-changed lib/main.dart lib/src/ test/ integration_test/
      - run: flutter analyze
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.13.0'
      - run: sudo apt-get update && sudo apt-get install -y lcov
      - run: flutter test --coverage
      - run: lcov --remove coverage/lcov.info 'lib/generated/*' > coverage/lcov_nogen.info
      - uses: codecov/codecov-action@v1
        with:
          files: coverage/lcov_nogen.info
          fail_ci_if_error: true
  integration-test-android:
    name: Integration tests
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        api-level:
          - 21
          - 29
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.13.0'
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: flutter test integration_test/app_test.dart
