name: Test

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master
      - dev

jobs:
  analyze:
    name: Static analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
          flutter-version: '1.23.0-18.1.pre'
      - run: flutter format -n --set-exit-if-changed lib/main.dart lib/src/ test/ test_driver/
      - run: flutter analyze
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
          flutter-version: '1.23.0-18.1.pre'
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true
  # drive-android:
  #   name: Integration tests
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       api-level:
  #         - 18
  #         - 28
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: beta
  #         flutter-version: '1.23.0-18.1.pre'
  #     - uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: ${{ matrix.api-level }}
  #         script: flutter drive --target test_driver/app.dart
